services:
  - type: cron
    name: hourly job
    runtime: node
    schedule: "15 * * * *"
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run job:hourly
    region: singapore
