services:
  # 日本時間の毎週土曜日の午前9時30分に実行
  - type: cron
    name: saturday job
    runtime: node
    schedule: "30 0 * * 6"
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run job:saturday
    region: singapore

  # 日本時間の毎週月曜日の午前9時30分に実行
  - type: cron
    name: monday job
    runtime: node
    schedule: "30 0 * * 1"
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run job:monday
    region: singapore

  # 日本時間の毎月1日の午後12時に実行
  # MEMO: バンド練習のメッセージは一旦いらんかなぁって感じなんでコメントアウト
  # - type: cron
  #   name: monthly job
  #   runtime: node
  #   schedule: "0 3 1 * *"
  #   buildCommand: pnpm install && pnpm run build
  #   startCommand: pnpm run job:monthly
  #   region: singapore

  # 日本時間の毎月25日の午前9時30分に実行
  - type: cron
    name: 25th job
    runtime: node
    schedule: "30 0 25 * *"
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run job:25th
    region: singapore
